services:
    barcelona:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - './:/var/www'
        networks:
            - barcelona-network
    mysql:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'barcelona-mysql:/var/lib/mysql'
        networks:
            - barcelona-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    mysql_test:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        env_file:
            - .env.testing
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'barcelona_test'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'barcelona-mysql_test:/var/lib/mysql'
        networks:
            - barcelona-network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    barcelona-network:
        driver: bridge
volumes:
    barcelona-volume:
        driver: local
    barcelona-mysql:
        driver: local
    barcelona-mysql_test:
        driver: local
